#!/usr/bin/env node
// Generates public/sw.js from scripts/sw-template.js with a
// per-build CACHE_NAME suffix.
//
// Chained into the `dev` and `build` scripts in package.json so every
// `next build` and `next dev` produces a fresh service worker whose
// cache name rotates per deploy.
//
// Why this exists: the cache name had to be bumped by hand in sw.js
// on every prod release, and the v0.2.5 brand refresh shipped invisibly
// because that didn't happen. Automating off the build SHA removes the
// human step.
//
// Source: NEXT_PUBLIC_BUILD_SHA env var. Provided by the Dockerfile
// builder stage (defaults to "dev"), forwarded from docker-compose.yml's
// `IMAGE_TAG` (the git SHA in CI deploys).

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const templatePath = join(here, "sw-template.js");
const outPath = join(here, "..", "public", "sw.js");

// 12 chars is enough to stay unique across years of deploys without
// bloating every cache-name comparison. "dev" identifies local builds
// so a SW from `pnpm dev` can't be mistaken for a stale prod one.
const rawSha = process.env.NEXT_PUBLIC_BUILD_SHA?.trim();
const version = rawSha && rawSha !== "dev" ? rawSha.slice(0, 12) : "dev";

const template = await readFile(templatePath, "utf8");

if (!template.includes("__BUILD_CACHE_VERSION__")) {
  // Fail loud — a template without the marker would silently produce
  // a SW with whatever string is hardcoded, defeating the whole point
  // of this script.
  console.error("[build-sw] sw-template.js is missing __BUILD_CACHE_VERSION__ marker");
  process.exit(1);
}

// Strip the TEMPLATE-ONLY block — it's metadata for human readers of
// the template, never meant to ship to the browser. Marker pair plus
// any whitespace and a single trailing blank line. Multiline mode so
// `.` spans newlines.
const stripped = template.replace(
  /\/\/ === TEMPLATE-ONLY-START ===[\s\S]*?\/\/ === TEMPLATE-ONLY-END ===\n*/m,
  ""
);

if (stripped === template) {
  console.error("[build-sw] sw-template.js is missing the TEMPLATE-ONLY marker pair");
  process.exit(1);
}

const generatedHeader =
  "// GENERATED at build time from apps/web/scripts/sw-template.js.\n" +
  "// DO NOT EDIT THIS FILE. Edit the template and re-run `pnpm build:sw`.\n\n";

const body = stripped.replace(/__BUILD_CACHE_VERSION__/g, version);
const out = generatedHeader + body;

await mkdir(dirname(outPath), { recursive: true });
await writeFile(outPath, out, "utf8");

console.log(`[build-sw] wrote ${outPath} — CACHE_NAME=slothbox-shell-${version}`);
