// Password-based key derivation + AEAD-key combiner.
//
// Two distinct primitives live in this module:
//
//   1. `deriveKeyFromPassword(password, salt, opsLimit, memLimit)`
//      — Argon2id. Hardens a human password into a 32-byte uniform key.
//      Runs in the BROWSER, never on the server. The server only stores
//      the salt + the cost parameters (`opsLimit`, `memLimit`).
//
//   2. `deriveAeadKey({ fragmentKey, passwordKey? })`
//      — BLAKE2b-keyed combiner. Mixes the URL-fragment key with the
//      password-derived key into the actual AEAD encryption key. When
//      no password is set, returns `fragmentKey` unchanged so a v0.1
//      share remains decryptable (backwards compatibility).
//
// Why this split:
//   - Argon2id is the slow, memory-hard step. It runs once when the
//     sender sets the password and once when the recipient enters it.
//     Storing its output (`passwordKey`) would mean the server could
//     decrypt — instead the output stays in the browser only.
//   - BLAKE2b-keyed is the fast combiner. It binds `fragmentKey` and
//     `passwordKey` into a single key so an attacker who gets one but
//     not the other learns nothing about the AEAD key.
//
// Cryptographic construction for password-protected shares (locked):
//
//     aead_key = BLAKE2b-keyed(
//         message = AEAD_KDF_LABEL || 0x00 || passwordKey,
//         key     = fragmentKey,
//         length  = 32
//     )
//
// The `AEAD_KDF_LABEL` prefix provides domain separation against any
// future protocol that might also call BLAKE2b on a similar input. The
// trailing `0x00` byte separates the label from the passwordKey
// material so a future label extension can never produce the same
// concatenation as a previous version on the same input.
//
// Audited primitives only — see `packages/crypto-core/src/index.ts`
// header for the package-wide rule.

import sodium from "libsodium-wrappers-sumo";
import { concatBytes, stringToBytes } from "./utils.js";

let ready: Promise<void> | null = null;
async function ensureReady(): Promise<void> {
  if (!ready) {
    ready = sodium.ready;
  }
  await ready;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Argon2id salt size. Matches libsodium's `crypto_pwhash_SALTBYTES` (16).
 * Per-share, never reused, generated by `generateSalt()` at share-create time.
 */
export const SALT_BYTES = 16;

/**
 * Argon2id output size. We always derive 32 bytes — same length as the
 * XChaCha20-Poly1305 key — so the output is the right size to feed
 * straight into BLAKE2b-keyed without truncation.
 */
export const DERIVED_KEY_BYTES = 32;

/**
 * Output size of `deriveAeadKey`. Matches XChaCha20-Poly1305 key length.
 * Re-exported as `AEAD_KEY_BYTES` for callers that want a name closer to
 * how they use it.
 */
export const AEAD_KEY_BYTES = 32;

/**
 * Default Argon2id parameters for password-protected shares (v0.2).
 *
 * These match libsodium's `crypto_pwhash_OPSLIMIT_MODERATE` and
 * `crypto_pwhash_MEMLIMIT_MODERATE` (3 ops, 64 MiB). At those settings
 * one derivation is ~250 ms on a 2022 laptop — fast enough that a user
 * doesn't perceive lag, slow enough that an offline brute-forcer holding
 * the ciphertext still has to pay ~250 ms per guess.
 *
 * Increasing the defaults requires a coordinated bump:
 *   - bump these constants here (callers that don't override pick them up);
 *   - update the migration 0005 CHECK bounds if the new values exceed them;
 *   - keep the OLD values stored on existing share rows — `deriveAeadKey`
 *     re-derives per-share with whatever was stored, so old shares stay
 *     decryptable.
 */
export const DEFAULT_OPS_LIMIT = 3;
export const DEFAULT_MEM_LIMIT_BYTES = 64 * 1024 * 1024; // 64 MiB
export const DEFAULT_MEM_LIMIT_KIB = DEFAULT_MEM_LIMIT_BYTES / 1024;

/**
 * Domain-separation label baked into `deriveAeadKey`'s BLAKE2b input.
 * Encodes the protocol family + a version tag so a future construction
 * change can never produce the same key as a previous one for the same
 * `(fragmentKey, passwordKey)` pair. The `v1` here is independent of the
 * SemVer release — it ticks only when the AEAD-KDF construction itself
 * changes.
 */
export const AEAD_KDF_LABEL = stringToBytes("slothbox-aead-kdf-v1");

/** Zero byte separator between the label and the password-key material. */
const AEAD_KDF_SEPARATOR = new Uint8Array([0x00]);

// ---------------------------------------------------------------------------
// Random salt
// ---------------------------------------------------------------------------

/**
 * Generate a fresh 16-byte Argon2id salt. Each password-protected share
 * gets its own salt — never reuse one across shares (that's the salt's
 * entire job).
 */
export async function generateSalt(): Promise<Uint8Array> {
  await ensureReady();
  return sodium.randombytes_buf(SALT_BYTES);
}

// ---------------------------------------------------------------------------
// Argon2id
// ---------------------------------------------------------------------------

/**
 * Stretch a UTF-8 password into a 32-byte uniform key via Argon2id.
 *
 * Caller invariants:
 *   - `salt` MUST be {@link SALT_BYTES} bytes (16).
 *   - `password` MUST be non-empty. We reject zero-length passwords
 *     because a no-password share should set `passwordProtected = false`
 *     instead of password-protecting with the empty string.
 *
 * Outputs `DERIVED_KEY_BYTES` (32) bytes, suitable for feeding straight
 * into `deriveAeadKey` as `passwordKey`.
 *
 * Why Argon2id (not Argon2i, not bcrypt, not scrypt):
 *   - Argon2id is the PHC-recommended general-purpose variant; it mixes
 *     Argon2i's side-channel resistance for the first half of memory
 *     access with Argon2d's GPU resistance for the second half.
 *   - bcrypt has a 72-byte password limit and is single-threaded only.
 *   - scrypt is fine, but Argon2id is the modern default and what
 *     libsodium's `crypto_pwhash` returns by default since libsodium
 *     1.0.15.
 */
export async function deriveKeyFromPassword(params: {
  password: string;
  salt: Uint8Array;
  opsLimit?: number;
  memLimit?: number;
}): Promise<Uint8Array> {
  await ensureReady();

  if (params.salt.length !== SALT_BYTES) {
    throw new Error(`salt must be ${SALT_BYTES} bytes`);
  }
  if (params.password.length === 0) {
    throw new Error("password must not be empty");
  }

  return sodium.crypto_pwhash(
    DERIVED_KEY_BYTES,
    params.password,
    params.salt,
    params.opsLimit ?? DEFAULT_OPS_LIMIT,
    params.memLimit ?? DEFAULT_MEM_LIMIT_BYTES,
    sodium.crypto_pwhash_ALG_ARGON2ID13
  );
}

// ---------------------------------------------------------------------------
// AEAD-key combiner
// ---------------------------------------------------------------------------

/**
 * Compute the AEAD encryption key from the URL-fragment key and an optional
 * password-derived key.
 *
 * When `passwordKey` is omitted (or null/undefined), this returns
 * `fragmentKey` byte-for-byte — i.e. the v0.1 behavior where the URL
 * fragment IS the encryption key. That preserves the trust boundary for
 * the no-password path and means the round-trip is byte-identical to
 * how the encryption / decryption code worked before migration 0005.
 *
 * When `passwordKey` is present, the AEAD key is:
 *
 *     BLAKE2b-keyed(
 *         message = "slothbox-aead-kdf-v1" || 0x00 || passwordKey,
 *         key     = fragmentKey,
 *         length  = 32
 *     )
 *
 * Both inputs are required to reproduce the key. An attacker with only
 * the URL fragment cannot brute-force the password offline through the
 * BLAKE2b stage (the passwordKey is Argon2id output, 256 bits uniform);
 * an attacker with only the password cannot derive the AEAD key without
 * the 256-bit fragment.
 *
 * @param params.fragmentKey  the 32-byte key carried in the URL fragment
 * @param params.passwordKey  the 32-byte Argon2id output from `deriveKeyFromPassword`,
 *                            or null/undefined for no-password shares
 *
 * @throws if `fragmentKey` is not exactly 32 bytes, or `passwordKey` is
 *         present but not exactly 32 bytes.
 */
export async function deriveAeadKey(params: {
  fragmentKey: Uint8Array;
  passwordKey?: Uint8Array | null;
}): Promise<Uint8Array> {
  await ensureReady();

  if (params.fragmentKey.length !== AEAD_KEY_BYTES) {
    throw new Error(`fragmentKey must be ${AEAD_KEY_BYTES} bytes`);
  }

  if (params.passwordKey == null) {
    // No password — the URL-fragment key IS the AEAD key. Copy into a
    // fresh Uint8Array so callers can't accidentally mutate the input
    // by mutating the output (the libsodium output is a fresh array;
    // we match that semantic here).
    return new Uint8Array(params.fragmentKey);
  }

  if (params.passwordKey.length !== AEAD_KEY_BYTES) {
    throw new Error(`passwordKey must be ${AEAD_KEY_BYTES} bytes`);
  }

  const message = concatBytes(AEAD_KDF_LABEL, AEAD_KDF_SEPARATOR, params.passwordKey);
  // crypto_generichash with a `key` parameter is BLAKE2b-keyed —
  // libsodium docs § "Key derivation" → "Generic key derivation".
  return sodium.crypto_generichash(AEAD_KEY_BYTES, message, params.fragmentKey);
}
